# 生产环境配置文件
server:
  port: 8288

spring:
  redis:
    host: localhost
    port: 6479
    jedis:
      pool:
        min-idle: 0
        max-idle: 100
        
  mongodb:
    custom:
      host: localhost
      port: 27017
      database: ForeSee
      # 用户认证的数据库
      authentication-database: admin
      # 连接池大小
      connections-per-host: 10
      # 最小连接池大小
      min-connections-per-host: 10

#eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://222.200.184.74:8888/eureka/

  instance:
    instance-id: springcloud-foresee-8288
    prefer-ip-address: true
    ip-address: 192.168.1.107
